name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Get version from pom.xml
        id: get-version
        run: echo "::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CD_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ github.repository }}:${{ steps.get-version.outputs.version }} .
          docker tag ${{ github.repository }}:${{ steps.get-version.outputs.version }} ghcr.io/${{ github.repository }}:${{ steps.get-version.outputs.version }}

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}:${{ steps.get-version.outputs.version }}
